### ISSUE TITLE
Suggestion: migrating data to Parse for greater flexibility

### ISSUE THREAD

**Issue by dcgoss** [kirkbyo/Alpha#1]
From looking at your app's model I think it would benefit greatly from a backend with parse.com. Instead of having to update your app every time you add new quotes or phrases, you can simply have the app fetch your content from Parse when the app opens. That way, if you wanted to add a new quote/phrase/etc. you can just add it in the Parse data browser and all your users will receive that new content immediately, no update required. Think of the app as more of a client, and less of a database.

**Comment by ozziek** [comment]
Hey,

I completely agree with you that Alpha should have a backend in place that holds all the quotes, fortune and words. The problem encountered when I attempted to add this new feature a while back was that most of Alpha's users are not connected to the internet when using the app and most likely do not have 3G/LTE turned on in the settings for Alpha as well. I might give this another try sometime soon, but instead this time have the quotes, fortunes and words storred locally instead. 

Ozzie

**Comment by dcgoss** [comment]
Understandable! Actually, Parse caches objects for when there is no connectivity, and they just released a new feature called [Local Datastore](https://parse.com/docs/ios_guide#localdatastore/iOS) that is a more comprehensive version of this, with support for queries, saves, etc. This enables full functionality of the app without any network connection. It seems to me that this could be implemented fairly easily, however I am unaware of any future direction you might have for Alpha at this point.

**Comment by dcgoss** [comment]
Quote contributions in Github could still be maintained by migrating the content to a .txt file or the like.

**Comment by ozziek** [comment]
I was unaware that Parse actually had that feature. Currently as for direction for Alpha, I did not really have any more big changes that I was planning on implementing in the future for Alpha. I am currently learning Ruby and more specifically the Ruby on Rails framework to maybe build my own backend service for Alpha and any future apps.

If you are interested in implementing this feature, feel free to fork the repo and create a new branch for this feature. If you would need any help along the way I would be happy to help.

**Comment by dcgoss** [comment]
Cool! The only hitch I can see is that it would require a Parse app account, and I would need to create that account in a way where I can access it but yet I can still transfer to you later. Perhaps I could create an account just for the app and then give the credentials to you in the future. It may be a bit before I have the time to try and implement this, but I would certainly like to try at some point.

**Comment by ozziek** [comment]
There is no rush for this feature so take your time. Regarding the Parse account, I will create an account sometime today and then email you the login info. :)

**Comment by ozziek** [comment]
I just finished creating the Parse App for Alpha. I invited to the app with email listed on your Github profile. Let me know if you have any troubles accepting the request.
